### ISSUE TITLE
Additional Tests: Add dedicated tests for Arazzo and AsyncAPI 

### ISSUE THREAD

**Issue by frankkilcommins** [stoplightio/vscode-spectral#241]
**Chore summary**
Ensure that we exercise the Arazzo and AsyncAPI core rulesets as part of the extension tests

**Tasks**
- [ ] Add dedicated fixtures
- [ ] Extended contexts based on above
- [ ] Add tests for Arazzo
- [ ] Add tests for AsyncAPI
